name: macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
defaults:
  run:
    working-directory: ./Horse Isle Server

jobs:
  build:

    runs-on: 	macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore
      
      
    - name: Build mac-64
      continue-on-error: false
      run: |
        dotnet publish -p:PublishProfile=MacOS.pubxml
        cp ../DataCollection/*.json "HorseIsleServer/bin/x64/MacOS/net5.0/osx-x64/publish/"
        cp ../DataCollection/*.MAP "HorseIsleServer/bin/x64/MacOS/net5.0/osx-x64/publish/"
        mkdir "HorseIsleServer/bin/x64/MacOS/net5.0/osx-x64/publish/www"
        cp -R ../WebInterface/* "HorseIsleServer/bin/x64/MacOS/net5.0/osx-x64/publish/www"
    
    - name: upload mac-64
      uses: actions/upload-artifact@v2
      with:
        name: mac-x64
        path: Horse Isle Server/HorseIsleServer/bin/x64/MacOS/net5.0/osx-x64/publish/
